development:
  cloud_name: <%= ENV['cloud_name'] %>
api_key: <%= ENV['api_key'] %>
api_secret: <%= ENV['api_secret'] %>



test:
cloud_name: <%= ENV['cloud_name'] %>
api_key: <%= ENV['api_key'] %>
api_secret: <%= ENV['api_secret'] %>
